apiVersion: v1
kind: Namespace
metadata:
  name: kamaji-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: clastix
  namespace: kamaji-system
spec:
  interval: 1m
  url: https://clastix.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kamaji
  namespace: kamaji-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kamaji
      sourceRef:
        kind: HelmRepository
        name: clastix
        namespace: kamaji-system
      version: 0.10.2
      interval: 1m
