apiVersion: v1
kind: Namespace
metadata:
  name: kamaji-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: clastix
  namespace: kamaji-system
spec:
  interval: 1m
  url: https://github.com/butterneck/kamaji
  ref:
    branch: issue/265
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kamaji
  namespace: kamaji-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./charts/kamaji
      sourceRef:
        kind: GitRepository
        name: clastix
        namespace: kamaji-system
      # version: 0.11.0
      interval: 1m
      reconcileStrategy: Revision
